### ISSUE TITLE
KITTI Dataset File Structure

### ISSUE THREAD

**Issue by Rhinozz** [PKUVDIG/SAMPLING#1]
First off, fantastic paper!

I'm trying to replicate your inferences on my machine and have gotten to the point of preparing data. However, the format provided in the README is very ambiguous:

```
${ROOT}
  |-- data
  `-- |-- kitti
      `-- |-- image
          |   |-- training
          |   |-- |-- image_00
          |   |-- |-- |-- 0000
          |   |-- |-- |-- ...
          |-- |-- testing
          |-- label
          |   |-- 0000.txt
          |   |-- ...
          `-- calib
```

What goes in "testing"? (Is it just 4 images from the original dataset, as you mention in your paper?) Which folder do you get the labels from? Which files go in the "calib" folder, if any?

**Comment by PKUVDIG** [comment]
We built the dataset based on the KITTI raw dataset, which can be downloaded from [here](https://www.cvlibs.net/datasets/kitti/raw_data.php). The test set can be directly randomly extracted from the raw dataset, so the test does not need to be explicitly separated out, it can be unified as one “images” file together with train set. We will update the organization of the dataset, which may make it clearer. And more details will be announced after completion of the organization.
BTW: the labels are not necessary, so don't worry about that.
